name: Facebook Fuel Bot

on:
  schedule:
    - cron: '*/10 * * * *' # รันทุก 10 นาที
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-fb-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Tools
        run: pip install requests beautifulsoup4 selenium webdriver-manager pytz
        
      - name: Run Python Code
        env:
          MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}
        run: python main.py
        
      - name: Save Data State
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data_fb.json
          git commit -m "update facebook data state" || echo "No changes"
          git push
